<?php

namespace ShopBundle\Repository;

use ShopBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllPublishedProductsWithStock() {
      
       $qb = $this->getEntityManager()->createQueryBuilder();
       $qb->select('p')
               ->from(Product::class,'p')
                ->where( 
                         $qb->expr()->gt('p.stock', '0'),
                         $qb->expr()->eq('p.published', '1')
                        )                
                ->getQuery();       
        $query = $qb->getQuery();
        $products = $query->getResult();
        return $products;
    }
    
    public function findAllProductsFromCategory($id){
       $qb = $this->getEntityManager()->createQueryBuilder();
       $qb->select('p')
               ->from(Product::class,'p')
                ->where( 
                        $qb->expr()->eq('p.category', ':id'),
                        $qb->expr()->gt('p.stock', '0'),
                         $qb->expr()->eq('p.published', '1')
                        )
                ->setParameter('id', $id)
                ->getQuery();       
        $query = $qb->getQuery();
        $products = $query->getResult();
        return $products;
    }

}
