<?php

namespace ShopBundle\Repository;

/**
 * PromoTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
