<?php

namespace ShopBundle\Repository;

/**
 * PromotionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
