# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:   
    app.product_modules:
        class:     ShopBundle\Service\ProductModules
        arguments: ['@doctrine.orm.entity_manager']
    app.stats_generator:
        class:     ShopBundle\Service\StatsGenerator
        arguments: ['@doctrine.orm.entity_manager']
